src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java, src/main/java/org/matsim/pt2matsim/mapping/PseudoRoutingImpl.java, src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersStandard.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/PseudoGraphImpl.java, src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java, src/main/java/org/matsim/pt2matsim/osm/lib/OsmDataImpl.java, src/main/java/org/matsim/pt2matsim/plausibility/PlausibilityCheck.java, src/main/java/org/matsim/pt2matsim/plausibility/log/AbstractPlausibilityWarning.java, src/main/java/org/matsim/pt2matsim/plausibility/log/ArtificialLinkWarning.java, src/main/java/org/matsim/pt2matsim/plausibility/log/DirectionChangeWarning.java, src/main/java/org/matsim/pt2matsim/plausibility/log/PlausibilityWarning.java, src/main/java/org/matsim/pt2matsim/plausibility/log/TravelTimeWarning.java, src/main/java/org/matsim/pt2matsim/run/CheckMappedSchedulePlausibility.java, src/main/java/org/matsim/pt2matsim/tools/CoordTools.java, src/main/java/org/matsim/pt2matsim/tools/GtfsTools.java, src/main/java/org/matsim/pt2matsim/tools/MiscUtils.java, src/main/java/org/matsim/pt2matsim/tools/NetworkTools.java, src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java, src/main/java/org/matsim/pt2matsim/tools/debug/ScheduleCleaner.java, src/main/java/org/matsim/pt2matsim/workbench/Asheville.java, src/main/java/org/matsim/pt2matsim/workbench/ZVVexample.java, src/test/java/org/matsim/pt2matsim/tools/CoordToolsTest.java
- updated plausibility check, fixed link direction difference calculations
- Fixed GtfsFeed conversion creating multiple departures for the same time
- gtfs route short name as name for matsim transit line
- ptmapper: minimal travel cost is always > 0
=> Improved plausibility check, misc. fixes

pom.xml, src/main/java/org/matsim/pt2matsim/run/CheckMappedSchedulePlausibility.java, src/main/java/org/matsim/pt2matsim/run/gis/Network2Geojson.java, src/main/java/org/matsim/pt2matsim/run/gis/Network2ShapeFile.java, src/main/java/org/matsim/pt2matsim/run/gis/Schedule2ShapeFile.java, src/main/java/org/matsim/pt2matsim/tools/MiscUtils.java, src/main/java/org/matsim/pt2matsim/tools/debug/ExtractDebugSchedule.java, src/main/java/org/matsim/pt2matsim/workbench/Asheville.java, src/main/java/org/matsim/pt2matsim/workbench/PTMapperShapesExample.java, src/main/java/org/matsim/pt2matsim/workbench/ZVVexample.java, src/test/java/org/matsim/pt2matsim/run/gis/Network2GeojsonTest.java
Since shapefiles are quite tedious... http://switchfromshapefile.org/
=> matsim network to geojson converter

.travis.yml, README.md, pom.xml
A shaded jar which includes all dependencies is deployed on the next release. Fixes #24
=> standalone jar

pom.xml, src/main/java/org/matsim/pt2matsim/config/OsmConverterConfigGroup.java, src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java, src/main/java/org/matsim/pt2matsim/run/CreateDefaultOsmConfig.java
Fixes #27 
https://stackoverflow.com/questions/27429097/geotools-cannot-find-hsql-epsg-db-throws-error-nosuchauthoritycodeexception#27431381
=> Shaded geotools

src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersOsmAttributes.java, src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersStandard.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/LinkSequence.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/PseudoScheduleImpl.java, src/main/java/org/matsim/pt2matsim/run/gis/Network2Geojson.java, src/main/java/org/matsim/pt2matsim/run/gis/Schedule2Geojson.java, src/test/java/org/matsim/pt2matsim/run/gis/Schedule2GeojsonTest.java, src/test/java/org/matsim/pt2matsim/tools/ScheduleToolsTest.java
Added independent NetworkRoute implementation (necessary for matsim 0.10.0)
Geojson network is written to one file, same for geojson schedule. Separate write methods are still available.
=> LinkSequence class, single geojson files

src/main/java/org/matsim/pt2matsim/run/gis/Network2Geojson.java, src/main/java/org/matsim/pt2matsim/run/gis/Schedule2Geojson.java, src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java, src/test/java/org/matsim/pt2matsim/run/gis/Schedule2GeojsonTest.java, src/test/java/org/matsim/pt2matsim/tools/ScheduleToolsTest.java
=> SetFreespeedBasedOnSchedule

src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java, src/main/java/org/matsim/pt2matsim/gtfs/lib/ServiceImpl.java
=> trim gtfs time strings

src/main/java/org/matsim/pt2matsim/editor/BasicScheduleEditor.java, src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java, src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java, src/main/java/org/matsim/pt2matsim/mapping/PTMapper.java, src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersStandard.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/PseudoScheduleImpl.java, src/main/java/org/matsim/pt2matsim/plausibility/StopFacilityHistogram.java, src/main/java/org/matsim/pt2matsim/tools/PTMapperTools.java, src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java, src/main/java/org/matsim/pt2matsim/tools/debug/ScheduleCleaner.java, src/test/java/org/matsim/pt2matsim/gtfs/GtfsConverterTest.java, src/test/java/org/matsim/pt2matsim/gtfs/GtfsFeedImplTest.java, src/test/java/org/matsim/pt2matsim/tools/ScheduleToolsTest.java, test/gtfs-feed/transfers.txt
- GtfsConverter: Available transfers in a gtfs feed are converted to MATSim transfers. Closes #47
- PTMapper: All child stop facilities of a parent stop have transfers among each other (minTransferTime: 0).
=> Convert GTFS Transfers 

src/main/java/org/matsim/pt2matsim/tools/NetworkTools.java
=> Potential fix for #66

src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java
Line 597 raised an IndexOutOfBounds exception if the number of links is for some reason zero. Not sure if this should happen at all (maybe i used some wrong input data), but in any case it should not throw an IndexOutOfBounds exception here.
=> Number of links may be zero

src/main/java/org/matsim/pt2matsim/config/OsmConverterConfigGroup.java, src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java, src/test/java/org/matsim/pt2matsim/osm/NetworkLayerTest.java, src/test/java/org/matsim/pt2matsim/osm/RoutableSubnetworkTest.java
Fixes #80 . Some how Travis had a problem... let's see if this one works.
=> Routeable subnetworks

src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java, src/main/java/org/matsim/pt2matsim/osm/OsmTransitScheduleConverter.java, src/main/java/org/matsim/pt2matsim/osm/lib/Osm.java, src/main/java/org/matsim/pt2matsim/run/Osm2TransitSchedule.java
Dear Flavio,
I was testing the Osm2TransitSchedule and ran into a couple of issues that were solved by the changes in the PR. 
Please let me know if you disagree with anything.
Best,
Davi
=> Osm2TransitSchedule small changes

pom.xml, src/main/java/org/matsim/pt2matsim/run/gis/Network2ShapeFile.java, src/main/java/org/matsim/pt2matsim/run/gis/Schedule2ShapeFile.java, src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java, src/main/java/org/matsim/pt2matsim/tools/ShapeTools.java, src/main/java/org/matsim/pt2matsim/tools/debug/ScheduleCleaner.java, src/test/java/org/matsim/pt2matsim/plausibility/PlausibilityCheckTest.java, src/test/java/org/matsim/pt2matsim/tools/ScheduleToolsTest.java
Update to MATSim v11.0 from MATSim 0.10.0 (@dts-ait in #87 )
Fixed tests, closes #88
=> MATSim v11.0

src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java
=> include line number in gtfs file exception message

pom.xml, src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java
=> Catch missing way params

src/main/java/org/matsim/pt2matsim/config/OsmConverterConfigGroup.java, src/main/java/org/matsim/pt2matsim/osm/LinkGeometryExporter.java, src/main/java/org/matsim/pt2matsim/osm/NetworkGeometryExporter.java, src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java
=> add geometry export for simunto via and other GIS software (rebased)

src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java, src/main/java/org/matsim/pt2matsim/gtfs/lib/GtfsDefinitions.java, src/test/java/org/matsim/pt2matsim/gtfs/GtfsConverterTest.java, src/test/java/org/matsim/pt2matsim/gtfs/GtfsFeedImplTest.java, test/gtfs-feed/routes.txt
=> Keep extended route types

src/main/java/org/matsim/pt2matsim/config/OsmConverterConfigGroup.java, src/main/java/org/matsim/pt2matsim/config/PublicTransitMappingConfigGroup.java, src/main/java/org/matsim/pt2matsim/editor/BasicScheduleEditor.java, src/main/java/org/matsim/pt2matsim/examples/Workflow.java, src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java, src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java, src/main/java/org/matsim/pt2matsim/gtfs/lib/StopImpl.java, src/main/java/org/matsim/pt2matsim/hafas/lib/BitfeldAnalyzer.java, src/main/java/org/matsim/pt2matsim/hafas/lib/ECKDATENReader.java, src/main/java/org/matsim/pt2matsim/hafas/lib/MinimalTransferTimesReader.java, src/main/java/org/matsim/pt2matsim/mapping/PTMapper.java, src/main/java/org/matsim/pt2matsim/mapping/PseudoRoutingImpl.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/LinkSequence.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/PseudoRouteStopImpl.java, src/main/java/org/matsim/pt2matsim/run/CheckMappedSchedulePlausibility.java, src/main/java/org/matsim/pt2matsim/run/ExampleWorkflow.java, src/main/java/org/matsim/pt2matsim/run/Gtfs2TransitSchedule.java, src/main/java/org/matsim/pt2matsim/run/Hafas2TransitSchedule.java, src/main/java/org/matsim/pt2matsim/run/Osm2MultimodalNetwork.java, src/main/java/org/matsim/pt2matsim/run/PublicTransitMapper.java, src/main/java/org/matsim/pt2matsim/run/gis/Network2Geojson.java, src/main/java/org/matsim/pt2matsim/run/gis/Schedule2Geojson.java, src/main/java/org/matsim/pt2matsim/tools/NetworkTools.java, src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java, src/main/java/org/matsim/pt2matsim/tools/debug/ScheduleCleaner.java, src/test/java/org/matsim/pt2matsim/gtfs/GtfsConverterTest.java, src/test/java/org/matsim/pt2matsim/hafas/HafasConverterTest.java, src/test/java/org/matsim/pt2matsim/mapping/PTMapperShapesTest.java
Some refactoring, shouldn't break any existing code
=> Code cleanup

src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java
=> Only allow transit routes with at least two stops

.gitignore, pom.xml
As noted in #87 
Plus add files to .gitignore
=> remove geotools dependencies

.github/workflows/maven-deploy.yml, .github/workflows/maven-test.yml, pom.xml, src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java, src/main/java/org/matsim/pt2matsim/hafas/HafasConverter.java, src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersOsmAttributes.java, src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersStandard.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/ArtificialLinkImpl.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/LinkSequence.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/PseudoRouteStop.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/PseudoRouteStopImpl.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/PseudoScheduleImpl.java, src/main/java/org/matsim/pt2matsim/plausibility/PlausibilityCheck.java, src/main/java/org/matsim/pt2matsim/tools/PTMapperTools.java, src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java, src/main/java/org/matsim/pt2matsim/tools/debug/ScheduleCleaner.java, src/test/java/org/matsim/pt2matsim/gtfs/GtfsConverterTest.java
Update to MATSim v12.0 from MATSim v11.0, now uses JDK 11.
Closes #124
=> MATSim v12.0

src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java
Made the InputStreamReader use UTF-8.
=> Made CSV reader use UTF-8

src/main/java/org/matsim/pt2matsim/config/PublicTransitMappingConfigGroup.java
=> Return joined set of scheduleFreespeedModes

pom.xml, src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java, src/main/java/org/matsim/pt2matsim/osm/LinkGeometryExporter.java
This pr just cherry-picked the latest updates from the master-branch to the matsim-14-snapshot branch.
=> Updates from master branch

src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java
> // assuming all days really do follow monday in the file
Better to never assume anything... took me a while to figure this one out :smile:
=> fix: Allow arbitrary order of week days

pom.xml, src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java
This pr applies the patch from #167 into the master branch, because it was still missing there.
=> Add network mode to vehicleType

src/main/java/org/matsim/pt2matsim/mapping/PseudoRoutingImpl.java
When generating pseudo routes with [`PseudoRoutingImpl`](https://github.com/matsim-org/pt2matsim/blob/722542813caf7061708194472171d7c45406d3b7/src/main/java/org/matsim/pt2matsim/mapping/PseudoRoutingImpl.java#L47), all TransitLines are evenly distributed to the available threads. 
https://github.com/matsim-org/pt2matsim/blob/722542813caf7061708194472171d7c45406d3b7/src/main/java/org/matsim/pt2matsim/mapping/PTMapper.java#L177-L181
As the TransitLines have a different number of TransitRoutes - and computation time scales somehow with the number of TransitRoutes - some threads finish their batch early while other are still working on other TransitLines. When working with large networks, this can result in pt2matsim running for days an a single core for the remaining TransitLines on that …
=> Relaxed parallel task assignment in PseudoRoutingImpl

src/main/java/org/matsim/pt2matsim/config/OsmConverterConfigGroup.java, src/main/java/org/matsim/pt2matsim/config/PublicTransitMappingConfigGroup.java, src/main/java/org/matsim/pt2matsim/hafas/lib/FPLANRoute.java, src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/PseudoGraphImpl.java, src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java, src/main/java/org/matsim/pt2matsim/osm/lib/Osm.java, src/main/java/org/matsim/pt2matsim/osm/lib/OsmDataImpl.java
* Use new instance of syntax
* Use isEmpty() instead of size() > 0
* Use log4j2 logging syntax
* Reorder private static modifiers
* Fix some typos in doc
=> Linting and typos

README.md, pom.xml
=> Release 24.4

pom.xml, src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java, src/test/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverterTurnRestrictionsTest.java, test/osm/Rudolfplatz_expected.xml
This removes all parsed DisallowedNextLinks that are not valid.
=> Clean network from invalid DisallowedNextLinks

pom.xml, src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java
This should resolve the build errors in #272.
=> Switch to Checker Framework Nullable

doc/defaultPTMapperConfig.xml, src/main/java/org/matsim/pt2matsim/config/PublicTransitMappingConfigGroup.java, src/main/java/org/matsim/pt2matsim/mapping/PTMapper.java, src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersStandard.java, src/main/java/org/matsim/pt2matsim/tools/NetworkTools.java, src/test/java/org/matsim/pt2matsim/mapping/PTMapperTest.java
We can now choose which router to use for routing, either SpeedyALT [default] or AStarLandmarks
For some use cases (entire Switzerland) AStar is 5-6 times faster for some tests
Related to #283
=> feat: add an option to choose the router

src/main/java/org/matsim/pt2matsim/config/TransportModeParameterSet.java
Was accidentally removed in #317 .
=> Add setNetworkModes to TransportModeParameterSet
