matsim-org/pt2matsim

README.md
pom.xml
src/main/assembly/assembly-release.xml

I added a release profile to the pom to create a runnable version of the pt2matsim tools (so they can be e.g. used on a cluster). Additionally I added some instructions to the README.

Standalone pom & instructions

---

pom.xml
src/main/java/org/matsim/pt2matsim/gtfs/GtfsFeedImpl.java

Adds a number of fixes:
- GTFS files are allowed to be preceded by a BOM, which needs to be skipped. This works now.
- Now extended GTFS route types are supported:
https://developers.google.com/transit/gtfs/reference/extended-route-types

Switzerland GTFS

---

src/main/java/org/matsim/pt2matsim/gtfs/lib/TransferImpl.java

This commit fixes a bug in the compare method where otherwise would a NullPointerException be thrown. Sample where this bug occured was from
here: https://daten.berlin.de/datensaetze/vbb-fahrplandaten-dezember-2017-bis-dezember-2018
DOKU: https://developers.google.com/transit/gtfs/reference/#transferstxt

it is possible for a min_transfer_time to be null.

---

src/main/java/org/matsim/pt2matsim/hafas/lib/FPLANReader.java
src/main/java/org/matsim/pt2matsim/hafas/lib/OperatorReader.java
src/main/java/org/matsim/pt2matsim/hafas/lib/StopReader.java

I think the most sensible configuration here is to always assume input as UTF-8, at least with the HAFAS 2017 and 2018 this works. Maybe there has been a change somewhere in the past.

Always assume UTF-8 as encoding for HAFAS data

---

src/main/java/org/matsim/pt2matsim/hafas/HafasConverter.java

Fixes #32. Whenever an unknown vehicle type is requested, a warning is displayed.

Handle unknown HAFAS vehicle types without throwing an exception

---

src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java
src/main/java/org/matsim/pt2matsim/plausibility/MappingAnalysis.java
src/main/java/org/matsim/pt2matsim/run/gis/Schedule2Geojson.java
src/test/java/org/matsim/pt2matsim/gtfs/GtfsConverterTest.java

GTFS converter first creates all transit routes based on trips. Afterwards, transit routes with equal stop sequences and departure offsets are combined by adding departures. This is a change from previous behaviour where departure offsets were ignored. Transit routes with similar but unequal departure offsets should be combined in a later step (not implemented in pt2matsim).
Plus some minor fixes.

Convert gtfs trips to transitRoutes one to one

---

src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java

The default of 50 is appropriate for buses or some trams, but mass rail transit likely needs more.

Give rail vehicles more capacity

---

README.md
src/main/java/org/matsim/pt2matsim/plausibility/NearbyLinkAnalysis.java
src/main/java/org/matsim/pt2matsim/plausibility/PlausibilityCheck.java
src/main/java/org/matsim/pt2matsim/plausibility/log/ArtificialLinkWarning.java
src/main/java/org/matsim/pt2matsim/plausibility/log/DirectionChangeWarning.java
src/main/java/org/matsim/pt2matsim/plausibility/log/LoopWarning.java
src/main/java/org/matsim/pt2matsim/plausibility/log/TravelTimeWarning.java
src/main/java/org/matsim/pt2matsim/run/CheckMappedSchedulePlausibility.java
src/main/java/org/matsim/pt2matsim/tools/GeojsonTools.java
src/main/java/org/matsim/pt2matsim/workbench/PTMapperShapesExample.java
src/test/java/org/matsim/pt2matsim/plausibility/PlausibilityCheckTest.java

Plausibility checker now writes geojson files instead of [shapefiles](http://switchfromshapefile.org/), which allows for a cleaner output folder structure. Closes #37 
All warnings are written to the same file. Network and schedule files are also written to geojson. Added some doc and tests as well.

Plausibility check as geojson

---

pom.xml

Tested with java versions `1.8.0_171` and `10.0.2` so there doesn't seem to be any problem with backward compatibility. Fixes #64.

Make compatible with Java 9+

---

src/main/java/org/matsim/pt2matsim/editor/BasicScheduleEditor.java
src/main/java/org/matsim/pt2matsim/mapping/PTMapper.java
src/main/java/org/matsim/pt2matsim/mapping/Progress.java
src/main/java/org/matsim/pt2matsim/mapping/PseudoRoutingImpl.java
src/main/java/org/matsim/pt2matsim/mapping/linkCandidateCreation/LinkCandidateCreatorStandard.java
src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersFactory.java
src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersGtfsShapes.java
src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersOsmAttributes.java
src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersStandard.java
src/main/java/org/matsim/pt2matsim/tools/NetworkTools.java
src/main/java/org/matsim/pt2matsim/workbench/PTMapperShapesExample.java
src/main/java/org/matsim/pt2matsim/workbench/ZVVexample.java
src/test/java/org/matsim/pt2matsim/mapping/PTMapperShapesTest.java

I noticed that the parallelization is quite simple: There is one router and multiple thread accessing it while doing some minor additional stuff. When I run pt2matsim with 80 threads they are just waiting for each other most of the time. This PR brings two improvements:
- "True" parallelization, i.e. now there is one separate `ScheduleRouters` object in every thread and therefore no locking.
- More verbosity in the steps that take some time during the process by showing a progess indicator on a per-second basis.

Improve parallelization & increase verbosity

---

src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java
src/main/java/org/matsim/pt2matsim/tools/NetworkTools.java

What happened in that changed line is that the OSM converter created a consistent car+bus network, so if you take all car and bus links you get a connected network without dead ends and islands. Already this is not ideal, because later on MATSim will do something like
```java
new TransportModeNetworkFilter(originalNetwork).filter(roadNetwork, Collections.singleton("car"));
```
to determine the car network for its internal routing. So if some parts of the car network are only connected to a rest by a bus link, the network will fall apart. 
FIx: Here we now do not make sure we have a consistent car+bus network, but we make sure that we have a consistent car-only network where we put all others modes on top.
@polettif Did I miss any specific reason, why there currently is "car,bus"?

Fix inconsistent car network

---

src/main/java/org/matsim/pt2matsim/mapping/PTMapper.java

Throws an exception when there is a routing error. Before, threads were just silently killed.

Fix routing exception

---

src/main/java/org/matsim/pt2matsim/mapping/linkCandidateCreation/LinkCandidateCreatorStandard.java
src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/ArtificialLinkImpl.java
src/main/java/org/matsim/pt2matsim/tools/PTMapperTools.java
src/test/java/org/matsim/pt2matsim/mapping/PTMapperTest.java
src/test/java/org/matsim/pt2matsim/tools/NetworkToolsTest.java
src/test/java/org/matsim/pt2matsim/tools/ScheduleToolsTest.java

With this PR, the linkCandidateCreator finds no links if no transportRouteAssignment is configured (for the given schedule transport mode). Before, using `null` lead to all links being considered. Some tests are added/fixed along the way. Prompted by #70.

Empty transportModeAssignment creates artificial loop links 

---

src/main/java/org/matsim/pt2matsim/config/OsmConverterConfigGroup.java
src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java
src/main/java/org/matsim/pt2matsim/osm/lib/Osm.java
src/main/java/org/matsim/pt2matsim/workbench/Asheville.java
src/main/java/org/matsim/pt2matsim/workbench/ZVVexample.java
src/test/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverterTest.java
test/osm/GerasdorfArtificialLanesAndMaxspeed.osm

- both now also consider :forward and :backward tags
- maxspeed supports values in kph (default), mph, knots
- maxspeed supports the special values 'none' and 'walk'
- maxspeed always uses the first value if several values are given (semicolon-separated) -> removed the config option "guessFreeSpeed", which is no longer necessary because the parser handles multiple values properly
- lanes calculation respects bus, psv,.. lanes (as described in the OSM wiki)
- fixed lanes calculation on bidirectional ways (lanes-value was not divided by 2)
- many unit tests and a new .osm file with test streets

Improve maxspeed/freespeed and lanes extraction

---

src/main/java/org/matsim/pt2matsim/hafas/HafasConverter.java
src/main/java/org/matsim/pt2matsim/hafas/lib/ECKDATENReader.java
src/main/java/org/matsim/pt2matsim/hafas/lib/FPLANReader.java
src/main/java/org/matsim/pt2matsim/hafas/lib/FPLANRoute.java
src/main/java/org/matsim/pt2matsim/run/Hafas2TransitSchedule.java
src/main/java/org/matsim/pt2matsim/tools/VehicleTypeDefaults.java
src/main/java/org/matsim/pt2matsim/tools/debug/ScheduleCleaner.java

Fix for issue #98, also solves a todo in the hafasConverter
- a chosen date can now be included as a 5th parameter to the hafas convertor (optional)
- if provided, the dayNr is calculated and validated against the fahrplan start/end from the ECKDATEN

#98 Allow a schedule to be created from hafas for a particular date

---

pom.xml

As mentioned in #108 
@markusstraub simply removing the dependencies [(like you suggested)](https://github.com/matsim-org/pt2matsim/blob/update-osgeo/pom.xml#L36) didn't quite work. Or rather: I wasn't able to make it work, the dependencies were still "missing". However, I'd say it's not crucial to remove them.

update osgeo repository url

---

src/main/java/org/matsim/pt2matsim/config/OsmConverterConfigGroup.java

when loading the config it was taking PublicTransitMappingConfigGroup instead of the
OsmConverterConfigGroup, which caused that the parameter sets were not loaded from the config file

osm config loader fix

---

pom.xml
src/test/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverterTest.java
test/osm/Belgrade.osm

Should fix #135
MATSim should depend on a newer geotools version as well (#87, #130) but there's no way to immediately force a version bump.

re-add geotools dependency

---

pom.xml

Either new Java versions check more strictly if signature files fit to the provided jar, or now some dependencies of pt2matsim become signed jars. In any case, the shaded jar was not useable anymore due to signature issues. The provided fix makes sure that the shaded jar can still be used as before.

Fix packaging with shade plugin

---

pom.xml
src/main/java/org/matsim/pt2matsim/mapping/pseudoRouter/ArtificialLinkImpl.java

I'm not quite sure how [versioning is handled](https://github.com/matsim-org/matsim-libs/issues/1813) but I guess it's safe to bump MATSim to 13.0

Update to MATSim 13

---

src/main/java/org/matsim/pt2matsim/tools/NetworkTools.java

Since MATSim-PR1638, the NetworkFilterManager needs a NetworkConfigGroup as second argument.
See https://github.com/matsim-org/matsim-libs/commit/5a909af2dffd01a9579b974cbbcc3947265b9bb6#diff-8fec9d85cc54b8b4fa0c2cbe3af160ad2efda6116c375617fe2dc724337482d2R44

Adjust call to NetworkFilterManager for MATSim 14.0-SNAPSHOT

---

src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java

I noticed, that the created vehicles missed the networkMode from `VehicleTypeDefaults`.

Add network mode to vehicleType

---

src/main/java/org/matsim/pt2matsim/osm/LinkGeometryExporter.java

When setting `outputDetailedLinkGeometryFile` to true and using french (fr_FR) Locale, the exported WTK is wrong.
The problem should exist for other than the fr_FR locale that use `,` as their decimal separator in `String.format`
Before patch :
```
LinkId,Geometry
100,"LINESTRING(376532,13825 6682657,98988,376560,14865 6682668,79825,376573,79065 6682673,30999)"
```
After patch : 
```
LinkId,Geometry
100,"LINESTRING(376532.13825 6682657.98988,376560.14865 6682668.79825,376573.79065 6682673.30999)"
```

fix exported WTK format

---

pom.xml

This pr explicitly defines the used dependencies in the pom.xml.
Currently, running `mvn dependency:analyze` shows the following warnings, which can cause issues when using pt2matsim as a dependency.
```log
[WARNING] Used undeclared dependencies found:
[WARNING]    org.geotools:gt-opengis:jar:24.2:compile
[WARNING]    com.fasterxml.jackson.core:jackson-databind:jar:2.10.3:compile
[WARNING]    com.google.guava:guava:jar:30.0-jre:compile
[WARNING]    org.locationtech.jts:jts-core:jar:1.17.1:compile
[WARNING]    org.apache.logging.log4j:log4j-1.2-api:jar:2.17.1:compile
[WARNING] Unused declared dependencies found:
[WARNING]    org.geotools:gt-referencing:jar:24.2:compile
[WARNING]    org.geotools:gt-epsg-hsql:jar:24.2:compile
```

Explicitly specify Maven dependencies

---

pom.xml
src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersGtfsShapes.java
src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersOsmAttributes.java
src/main/java/org/matsim/pt2matsim/mapping/networkRouter/ScheduleRoutersStandard.java
src/main/java/org/matsim/pt2matsim/osm/lib/OsmFileReader.java

Bump MATSim to ~16.0~ 2024.0 when it is available

Bump MATSim to 2024.0

---

src/main/java/org/matsim/pt2matsim/hafas/HafasConverter.java
src/main/java/org/matsim/pt2matsim/osm/OsmTransitScheduleConverter.java
src/main/java/org/matsim/pt2matsim/run/gis/Network2ShapeFile.java
src/main/java/org/matsim/pt2matsim/run/gis/Schedule2ShapeFile.java
src/main/java/org/matsim/pt2matsim/tools/CoordTools.java
src/main/java/org/matsim/pt2matsim/tools/ScheduleTools.java
src/main/java/org/matsim/pt2matsim/tools/ShapeTools.java

* Use `VehicleUtils` for `accessTime`, `egressTime`, `doorOperationMode`
* Add missing `@Deprecated` annotation to `CoordTools.getBorderCrossType()`
* Remove unused `network` argument from `RouteUtils.createNetworkRoute(..)`
* Replace deprecated `ShapeFileWriter` with `GeoFileWriter`

Fix usage of deprecated methods and classes

---

pom.xml

From `geojson-jackson` version 1.8.1 on, it was necessary to add `com.fasterxml.jackson.core:jackson-annotations` as dependency.

Bump GeoJson-Jackson from 1.5 to 1.14

---

pom.xml
src/test/java/org/matsim/pt2matsim/editor/BasicScheduleEditorTest.java
src/test/java/org/matsim/pt2matsim/gtfs/GtfsConverterTest.java
src/test/java/org/matsim/pt2matsim/gtfs/GtfsFeedImplTest.java
src/test/java/org/matsim/pt2matsim/gtfs/GtfsRealFeedTest.java
src/test/java/org/matsim/pt2matsim/gtfs/SpaceIdTest.java
src/test/java/org/matsim/pt2matsim/hafas/HafasConverterTest.java
src/test/java/org/matsim/pt2matsim/hafas/HafasFplanTest.java
src/test/java/org/matsim/pt2matsim/mapping/PTMapperShapesTest.java
src/test/java/org/matsim/pt2matsim/mapping/PTMapperTest.java
src/test/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverterTest.java
src/test/java/org/matsim/pt2matsim/osm/RoutableSubnetworkTest.java
src/test/java/org/matsim/pt2matsim/osm/lib/AllowedTagsFilterTest.java
src/test/java/org/matsim/pt2matsim/plausibility/MappingAnalysisTest.java
src/test/java/org/matsim/pt2matsim/plausibility/PlausibilityCheckTest.java
src/test/java/org/matsim/pt2matsim/run/gis/Network2GeojsonTest.java
src/test/java/org/matsim/pt2matsim/run/gis/Schedule2GeojsonTest.java
src/test/java/org/matsim/pt2matsim/tools/CoordToolsTest.java
src/test/java/org/matsim/pt2matsim/tools/CsvToolsTest.java
src/test/java/org/matsim/pt2matsim/tools/GtfsToolsTest.java
src/test/java/org/matsim/pt2matsim/tools/NetworkToolsTest.java
src/test/java/org/matsim/pt2matsim/tools/ScheduleToolsTest.java
src/test/java/org/matsim/pt2matsim/tools/ShapeToolsTest.java

Some things I noticed and fixed:
- [`PlausibilityCheckTest`](https://github.com/matsim-org/pt2matsim/compare/junit5?expand=1#diff-0d57fda553c75ab9c6d70d067b6680ee9204dfc54ce812c9f220f6b930ea7f48) was accidentally using `org.locationtech.jts.util.Assert`.
- The `message` argument was not used in [`OsmMultimodalNetworkConverterTest.assertMaxspeed(..)`](https://github.com/matsim-org/pt2matsim/compare/junit5?expand=1#diff-94dfd45167f3de757530d91b940df0190d6c49d36185fb3d5d426bdbfc7e95fdL276)

Migrate from JUnit 4 to JUnit 5

---

src/main/java/org/matsim/pt2matsim/gtfs/GtfsConverter.java

Just a minor fix that moves the counting of routes until after all the cleaning and merging is done

fix route count attribute in case of using stoptimes instead of frequencies

---

pom.xml

This change adds explicit configuration of the Maven surefire and failsafe plugins. Now, executing `mvn test` and `mvn verify` will actually run unit/integration tests.

Add Maven surefire and failsafe plugins

---

test/Gtfs2TransitScheduleIT/testInfoInSchedule/schedule.xml
test/Gtfs2TransitScheduleIT/testNoAdditionalInfo/schedule.xml

The stop facilities were missing a `stopAreaId` attribute. This was not caught as this test was an integration test (`*IT.java`) and the Maven failsafe plugin was not specified previously (see #255).

Fix Gtfs2TransitScheduleIT

---

.github/workflows/maven-test.yml

Integration tests are now executed by the GitHub workflow.
#252 added the first integration test, but only `mvn test` was executed so test failures were not recognized.

Include integration tests in GitHub workflow

---

src/main/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverter.java
src/test/java/org/matsim/pt2matsim/osm/OsmMultimodalNetworkConverterTurnRestrictionsTest.java
src/test/java/org/matsim/pt2matsim/osm/OsmTurnRestrictionTest.java
test/osm/tr0_valid.osm
test/osm/tr1_invalid.osm
test/osm/tr2_valid.osm
test/osm/tr3_valid.osm
test/osm/tr4_valid.osm
test/osm/tr5_valid.osm
test/osm/tr6_valid.osm

This change revamps the parsing of turn restrictions and adds some tests for edge cases like `to` and `from` being the same way for u-turns and `via` being links and not nodes.

Improve parsing of turn restrictions as DisallowedNextLinks

---

.github/workflows/maven-release.yml

As of  https://github.com/actions/cache/discussions/1510, there are no changes to the parameters of the action despite bumping the version. This should close #268.

Bump actions/cache from v2 to v4
